### PR TITLE
Ensure deploy and main are in sync

### PR DESCRIPTION
**Pull request by Ostrzyciel**

### CODE REVIEW

**Comment by Ostrzyciel** [comment]
@rdzanyM please take a look at this, the deploy branch has an unusually large diff when comparing to main, which causes issues when we are merging new versions into deploy. If you made any meaningful changes on deploy, they should be brought to main as well. Thanks!

**Comment by rdzanyM** [comment]
That's because the deploy branch has DB with indices and some other changes required by the server. If it works locally I guess you can merge it.

**Comment by Ostrzyciel** [comment]
> That's because the deploy branch has DB with indices and some other changes required by the server. If it works locally I guess you can merge it.

Could you sort it out, please? The DB and the index can remain on the deploy branch as the only difference, but we should really avoid having to apply deploy-specific hacks. Thanks in advance.

**Comment by rdzanyM** [comment]
Idk, I merged it with db files and left it as that, because otherwise merging main into deploy would become problematic (if main was ahead with the commits removing the db)

**Comment by Ostrzyciel** [comment]
Right, I'll do it myself later. Thanks.

**Pull request merged**
