### PR TITLE
Older journals

### LINKED ISSUE #57: Implement the old scoring system (2017–2018)
Supposedly, in 2017–2018 there was a 0–50 point scale instead. I don't know anything more about it, we would have to investigate this further.

### PR DESCRIPTION
**Pull request by rdzanyM**
older journals are loaded into db.  
xlsx file was created manually by combining several pdf files.

### CODE REVIEW

**Comment by rdzanyM** [comment]
Some journals have previous points displayed, however, if a journal is not present in 2018+ data ('Ziemniak'), it is not searched (maybe because it has no domains as they were not specified in older data). It may be a desired behaviour but it's worth noting.
image

**Comment by Ostrzyciel** [comment]
Looks good, but maybe we should sort the dates in the sidebar table in the descending order? I think having the most recent value at the top would be more intuitive.

Also, maybe we could apply some styling to point values from the old system? For example:
* underline + data tooltip in the main results table
* [`abbr` HTML tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) for the plain table in the sidebar

In the tooltip just add a note that is from the old point system or whatever.

**Comment by rdzanyM** [comment]
That's how it looks now.   
image
image

**Comment by Ostrzyciel** [comment]
Bueno <3

**Pull request merged**
